const mongoose = require('mongoose');
const { APPROVAL_STATUSES } = require('../constants/admin');

const encontroSchema = new mongoose.Schema({
  nomeCompleto: { type: String, required: true },
  comoQuerSerChamado: { type: String, default: '' },
  genero: { type: String, enum: ['masculino', 'feminino', 'outros'], default: 'outros' },
  ejc: { type: String, required: true },
  ejcVinculadoId: { type: mongoose.Schema.Types.ObjectId, ref: 'Ejc', default: null },
  ejcVinculadoNome: { type: String, default: '', trim: true },
  qualEjcPertence: { type: String, default: '' },
  tipo: { type: String, enum: ['jovens', 'tios'], required: true },
  tiosCategoria: { type: String, enum: ['casal', 'solo', ''], default: '' },
  origemTios: { type: Boolean, default: false },
  tiosGrupoId: { type: String, default: '' },
  tioParceiroId: { type: mongoose.Schema.Types.ObjectId, ref: 'Encontro', default: null },
  equipeServiu: { type: [String], default: [] },
  equipeCoordenou: { type: [String], default: [] },
  temVeiculoProprio: { type: Boolean, default: false },
  logradouro: { type: String, required: true },
  bairro: { type: String, required: true },
  dataNascimento: { type: Date, required: true },
  telefone: { type: String, required: true },
  intolerante: { type: String, default: '' },
  ehAlergico: { type: String, enum: ['sim', 'nao'], default: 'nao' },
  alergiaDescricao: { type: String, default: '' },
  email: { type: String, required: true },
  temRelacionamento: { type: String, default: '' },
  instagram: { type: String, default: '' },
  foto: { type: String, required: true },
  observacoes: { type: String, default: '' },
  aprovado: { type: Boolean, default: false },
  statusAprovacao: { type: String, enum: APPROVAL_STATUSES, default: 'pendente' },
  lgpdConsentimento: { type: Boolean, default: false },
  lgpdConsentimentoData: { type: Date, default: null },
  lgpdConsentimentoIp: { type: String, default: '' },
  anonimizadoEm: { type: Date, default: null },
  dataCadastro: { type: Date, default: Date.now },
});

module.exports = mongoose.model('Encontro', encontroSchema);
